//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MohawkCollege.EHR.gpmr.Pipeline.Renderer.Deki {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MohawkCollege.EHR.gpmr.Pipeline.Renderer.Deki.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;docTemplate name=&quot;Clean&quot; author=&quot;Justin Fyfe&quot; output=&quot;text/html&quot; xmlns=&quot;http://marc.mohawkcollege.ca/hi&quot;&gt;
        ///
        ///
        ///  &lt;!-- Style is not currently supported for publishing to DEKI, need to figure out how to register a global style --&gt;
        ///  &lt;style&gt;
        ///    &lt;![CDATA[
        ///    
        ///    #gpmrSummaryDiv  
        ///        {
        ///          width:320px;
        ///          max-width:350px;
        ///        	z-index:10;
        ///        	float:right;
        ///        	border:solid 1px #3366cc;
        ///        	background-image:url(&apos;http://wiki2.marc-hi.ca/skins/deuce/lighty-blue/hea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string @__Default_nopub {
            get {
                return ResourceManager.GetString("__Default_nopub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;docTemplate name=&quot;Default&quot; author=&quot;Justin Fyfe&quot; output=&quot;text/html&quot; xmlns=&quot;http://marc.mohawkcollege.ca/hi&quot;&gt;
        ///
        ///  &lt;!-- Defines what goes on any outputted file, no matter what --&gt;
        ///  &lt;globalTemplate&gt;
        ///    &lt;![CDATA[
        ///		&lt;!-- 
        ///			This page was automatically generated using the General Purpose Mif Rendering Tool
        ///			using the DEKI-WIKI rendering extension.
        ///			
        ///			Rendered By: $user$
        ///			Rendered On: 01-09-2009 at $time$
        ///			Article Title: $value$
        ///		--&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///      .rightCol { padding: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Classic {
            get {
                return ResourceManager.GetString("Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;docTemplate name=&quot;Clean&quot; author=&quot;Justin Fyfe&quot; output=&quot;text/html&quot; xmlns=&quot;http://marc.mohawkcollege.ca/hi&quot;&gt;
        ///
        ///  
        ///  &lt;!-- Style is not currently supported for publishing to DEKI, need to figure out how to register a global style --&gt;
        ///  &lt;style&gt;
        ///    &lt;![CDATA[
        ///    
        ///    #gpmrSummaryDiv  
        ///        {
        ///          width:320px;
        ///          max-width:350px;
        ///        	z-index:10;
        ///        	float:right;
        ///        	border:solid 1px #3366cc;
        ///        	background-image:url(&apos;http://wiki2.marc-hi.ca/skins/deuce/lighty-blue/h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
    }
}
