//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MohawkCollege.EHR.gpmr.Pipeline.Renderer.RimbaCS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Licenses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Licenses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MohawkCollege.EHR.gpmr.Pipeline.Renderer.RimbaCS.Licenses", typeof(Licenses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * Copyright $year$, $org$
        /// * 
        /// * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you 
        /// * may not use this file except in compliance with the License. You may 
        /// * obtain a copy of the License at 
        /// * 
        /// * http://www.apache.org/licenses/LICENSE-2.0 
        /// * 
        /// * Unless required by applicable law or agreed to in writing, software
        /// * distributed under the License is distributed on an &quot;AS IS&quot; BASIS, WITHOUT
        /// * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
        /// * Licens [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string APACHE {
            get {
                return ResourceManager.GetString("APACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * Copyright (c) $year$, $org$
        /// * All rights reserved.
        /// * 
        /// * Redistribution and use in source and binary forms, with or without modification, are permitted provided that 
        /// * the following conditions are met:
        /// * 
        /// *    * Redistributions of source code must retain the above copyright notice, this list of conditions and 
        /// *       the following disclaimer.
        /// *    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions 
        /// *      and the following disclaimer in  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BSD {
            get {
                return ResourceManager.GetString("BSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * Copyright (c) $year$ $org$
        /// * 
        /// * Permission is hereby granted, free of charge, to any person
        /// * obtaining a copy of this software and associated documentation
        /// * files (the &quot;Software&quot;), to deal in the Software without
        /// * restriction, including without limitation the rights to use,
        /// * copy, modify, merge, publish, distribute, sublicense, and/or sell
        /// * copies of the Software, and to permit persons to whom the
        /// * Software is furnished to do so, subject to the following
        /// * conditions:
        /// * 
        /// * The [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MIT {
            get {
                return ResourceManager.GetString("MIT", resourceCulture);
            }
        }
    }
}
