//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MohawkCollege.EHR.gpmr.Pipeline.Renderer.Java {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Template {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Template() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MohawkCollege.EHR.gpmr.Pipeline.Renderer.Java.Template", typeof(Template).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * $license$
        /// */
        ///package $name$;
        ///
        ///import $apins$.interfaces.*;
        ///
        ////**
        /// * Autgenerated by GPMR $version$
        /// */
        ///public class JarInfo implements IGeneratedJarInfo {
        ///
        ///	public String getTitle() { return &quot;$name$&quot;; }
        ///	public String getGpmrVersion() { return &quot;$version$&quot;; }
        ///	public String getCompany() { return &quot;$org$&quot;; }
        ///	public String getCopyright() { return &quot;Copyright (C)  $year$&quot;; }
        ///	public String getVersion() { return &quot;1.0.0.0&quot;; }
        ///	public String getInformationalVersion() { return &quot;$mrversion$&quot;; } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssemblyInfo {
            get {
                return ResourceManager.GetString("AssemblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;classpath&gt;
        ///	&lt;classpathentry kind=&quot;src&quot; path=&quot;src&quot;/&gt;
        ///	&lt;classpathentry kind=&quot;con&quot; path=&quot;org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.6&quot;/&gt;
        ///	&lt;classpathentry kind=&quot;lib&quot; path=&quot;lib\org.marc.everest.jar&quot;/&gt;
        ///	&lt;classpathentry kind=&quot;output&quot; path=&quot;bin&quot;/&gt;
        ///&lt;/classpath&gt;
        ///.
        /// </summary>
        internal static string ClassPath {
            get {
                return ResourceManager.GetString("ClassPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;classpath&gt;
        ///	&lt;classpathentry kind=&quot;src&quot; output=&quot;target/classes&quot; path=&quot;src/main/java&quot;&gt;
        ///		&lt;attributes&gt;
        ///			&lt;attribute name=&quot;optional&quot; value=&quot;true&quot;/&gt;
        ///			&lt;attribute name=&quot;maven.pomderived&quot; value=&quot;true&quot;/&gt;
        ///		&lt;/attributes&gt;
        ///	&lt;/classpathentry&gt;
        ///	&lt;classpathentry excluding=&quot;**&quot; kind=&quot;src&quot; output=&quot;target/classes&quot; path=&quot;src/main/resources&quot;&gt;
        ///		&lt;attributes&gt;
        ///			&lt;attribute name=&quot;maven.pomderived&quot; value=&quot;true&quot;/&gt;
        ///		&lt;/attributes&gt;
        ///	&lt;/classpathentry&gt;
        ///	&lt;classpathentry kind=&quot;src&quot; o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassPathMaven {
            get {
                return ResourceManager.GetString("ClassPathMaven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// *
        /// * $license$
        /// *
        /// * Date: $date$ at $time$
        /// * Author: $author$
        /// * 
        /// * This file was automatically generated by the General Purpose Mif Rendering Tool $version$
        /// * Running on .NET CLR $clrversion$
        /// */
        ///
        ///.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project xmlns=&quot;http://maven.apache.org/POM/4.0.0&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd&quot;&gt;
        ///  &lt;modelVersion&gt;4.0.0&lt;/modelVersion&gt;
        ///  &lt;groupId&gt;org.marc.everest&lt;/groupId&gt;
        ///  &lt;artifactId&gt;$mrversion$&lt;/artifactId&gt;
        ///  &lt;version&gt;1.0&lt;/version&gt;
        ///  &lt;name&gt;$name$&lt;/name&gt;
        ///  &lt;description&gt;Autogenerated by GPMR $version$&lt;/description&gt;
        ///  &lt;dependencies&gt;
        ///  	&lt;dependency&gt;
        ///  		&lt;groupId&gt;org.marc.everest&lt;/groupId&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pom {
            get {
                return ResourceManager.GetString("Pom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Fri Jun 24 11:31:21 EDT 2011
        ///eclipse.preferences.version=1
        ///org.eclipse.jdt.core.compiler.codegen.inlineJsrBytecode=enabled
        ///org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.6
        ///org.eclipse.jdt.core.compiler.codegen.unusedLocal=preserve
        ///org.eclipse.jdt.core.compiler.compliance=1.6
        ///org.eclipse.jdt.core.compiler.debug.lineNumber=generate
        ///org.eclipse.jdt.core.compiler.debug.localVariable=generate
        ///org.eclipse.jdt.core.compiler.debug.sourceFile=generate
        ///org.eclipse.jdt.core.compiler.problem.assertIde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;projectDescription&gt;
        ///	&lt;name&gt;$name$&lt;/name&gt;
        ///	&lt;comment&gt;&lt;/comment&gt;
        ///	&lt;projects&gt;
        ///	&lt;/projects&gt;
        ///	&lt;buildSpec&gt;
        ///		&lt;buildCommand&gt;
        ///			&lt;name&gt;org.eclipse.jdt.core.javabuilder&lt;/name&gt;
        ///			&lt;arguments&gt;
        ///			&lt;/arguments&gt;
        ///		&lt;/buildCommand&gt;
        ///	&lt;/buildSpec&gt;
        ///	&lt;natures&gt;
        ///		&lt;nature&gt;org.eclipse.jdt.core.javanature&lt;/nature&gt;
        ///	&lt;/natures&gt;
        ///&lt;/projectDescription&gt;.
        /// </summary>
        internal static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;projectDescription&gt;
        ///	&lt;name&gt;$name$&lt;/name&gt;
        ///	&lt;comment&gt;&lt;/comment&gt;
        ///	&lt;projects&gt;
        ///	&lt;/projects&gt;
        ///	&lt;buildSpec&gt;
        ///		&lt;buildCommand&gt;
        ///			&lt;name&gt;org.eclipse.jdt.core.javabuilder&lt;/name&gt;
        ///			&lt;arguments&gt;
        ///			&lt;/arguments&gt;
        ///		&lt;/buildCommand&gt;
        ///		&lt;buildCommand&gt;
        ///			&lt;name&gt;org.eclipse.m2e.core.maven2Builder&lt;/name&gt;
        ///			&lt;arguments&gt;
        ///			&lt;/arguments&gt;
        ///		&lt;/buildCommand&gt;
        ///	&lt;/buildSpec&gt;
        ///	&lt;natures&gt;
        ///		&lt;nature&gt;org.eclipse.jdt.core.javanature&lt;/nature&gt;
        ///		&lt;nature&gt;org.eclipse.m2e.core.maven2Nature&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectFileMaven {
            get {
                return ResourceManager.GetString("ProjectFileMaven", resourceCulture);
            }
        }
    }
}
