//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARC.Everest.VisualStudio.Wizards {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WizardData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WizardData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MARC.Everest.VisualStudio.Wizards.WizardData", typeof(WizardData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Messages.
        /// </summary>
        internal static string COMT {
            get {
                return ResourceManager.GetString("COMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string FICR {
            get {
                return ResourceManager.GetString("FICR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Infrastructure.
        /// </summary>
        internal static string MCCI {
            get {
                return ResourceManager.GetString("MCCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory.
        /// </summary>
        internal static string POLB {
            get {
                return ResourceManager.GetString("POLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication.
        /// </summary>
        internal static string POME {
            get {
                return ResourceManager.GetString("POME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription.
        /// </summary>
        internal static string PORX {
            get {
                return ResourceManager.GetString("PORX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Registry.
        /// </summary>
        internal static string PRLO {
            get {
                return ResourceManager.GetString("PRLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Registry.
        /// </summary>
        internal static string PRPA {
            get {
                return ResourceManager.GetString("PRPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Registry.
        /// </summary>
        internal static string PRPM {
            get {
                return ResourceManager.GetString("PRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Infrastructure.
        /// </summary>
        internal static string QUQI {
            get {
                return ResourceManager.GetString("QUQI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent Managment.
        /// </summary>
        internal static string RCMR {
            get {
                return ResourceManager.GetString("RCMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Care.
        /// </summary>
        internal static string REPC {
            get {
                return ResourceManager.GetString("REPC", resourceCulture);
            }
        }
    }
}
